# Lightsheet Microscopy Image Processing Pipeline
# Conda Environment Specification (CONDA-ONLY, no pip in YAML)
#
# Creates separate environment: imaging_pipeline
# Python 3.11, independent from llm-inference
#
# Usage:
#   mamba env create -f environment_imaging.yml
#   mamba activate imaging_pipeline
#
# Hardware: AMD Threadripper 7970X + RTX Pro 6000 Blackwell (96GB VRAM)

name: imaging_pipeline

channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  # Python & Build Tools
  - python=3.11
  - pip
  - cython>=0.29.30
  - cmake>=3.25.0
  - git

  # Core Scientific Stack
  - numpy>=1.24.0
  - scipy>=1.10.0
  - scikit-image>=0.22.0
  - scikit-learn>=1.3.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - openpyxl>=3.1.0
  
  # Image I/O Foundations
  - h5py>=3.8.0
  - libtiff>=4.5.0
  - zstd>=1.5.5
  
  # Optional but useful for dev
  - ipython>=8.10.0
  - jupyter>=1.0.0
  - git

# NOTE: All pip packages installed AFTER environment creation
# See setup_imaging_pipeline.sh for pip install step
